name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # Configuration is managed via release-please-config.json and .release-please-manifest.json
          # Use a PAT with repo and workflow permissions
          # Create at: https://github.com/settings/tokens/new
          # Add as repository secret named RELEASE_PLEASE_TOKEN
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
