name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # The release type determines how versions are bumped and what files are updated
          release-type: node
          # Package name from package.json
          package-name: bingo-card-generator
