name: Test & Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Cache Bun dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install dependencies
      run: bun install

    - name: Cache Next.js build
      uses: actions/cache@v4
      with:
        path: |
          .next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-${{ hashFiles('**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-
          ${{ runner.os }}-nextjs-

    - name: Run lint
      run: bun run lint

    - name: Run tests with coverage
      run: NODE_OPTIONS='--experimental-vm-modules' bunx jest --coverage

    - name: Cache coverage reports
      uses: actions/cache@v4
      with:
        path: coverage
        key: ${{ runner.os }}-coverage-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-coverage-

    - name: Build application
      run: bun run build

    # Optional: Upload coverage to Codecov
    # Uncomment the following lines and add CODECOV_TOKEN to repository secrets
    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v4
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     files: ./coverage/coverage-final.json
    #     fail_ci_if_error: false
